### ISSUE TITLE
Training interrupted due to index out of bounds error

### ISSUE THREAD

**Issue by mon28** [hhk7734/tensorflow-yolov4#2]
Hi,

My training began successfully but got interrupted with the following error after some 30 steps.

```
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    pre_trained_weights=None,
  File "/data/mtare/darknet-py/venv/lib/python3.6/site-packages/yolov4/tf/__init__.py", line 286, in train
    for image_data, target in trainset:
  File "/data/mtare/darknet-py/venv/lib/python3.6/site-packages/yolov4/core/dataset.py", line 137, in __next__
    ) = self.preprocess_true_boxes(bboxes)
  File "/data/mtare/darknet-py/venv/lib/python3.6/site-packages/yolov4/core/dataset.py", line 373, in preprocess_true_boxes
    label[best_detect][yind, xind, best_anchor, :] = 0
IndexError: index 76 is out of bounds for axis 0 with size 76
```

 I don't think my data is inaccurate. Let me know what you think. @hhk7734

**Comment by hhk7734** [comment]
I'm doing other work, so I can't test it now.
Maybe, I'm going to see it this weekend or next week.

**Comment by hhk7734** [comment]
There seems to be no way for me to test this problem.
